name = "BAHH MINIGAMES 1.1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb4c375f124789b0e62d83d80ae7a34751871f2677d3cf3ed04bd9ef4f5b995e"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
